repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        # F821 Undefined name `node` - due to script nodes
        # F841 Local variable <> is assigned to but never used
        # E701 Multiple statements on one line (colon)
        # E741 Ambiguous variable name:
        args: [--fix, --exit-non-zero-on-fix, "--ignore=F821,F841,E701,E741"] 
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.10
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm==0.3.6