identifier = "com.luxonis.whisper"
app_version = "1.0.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3 python3-pip ffmpeg git libglib2.0-0 libgl1-mesa-glx wget xcb libportaudio2 libportaudiocpp0 portaudio19-dev" },
   
]

prepare_build_container = []

build_steps = ["pip3 install -r /app/requirements.txt --break-system-packages"]


entrypoint = ["bash", "-c", "python3 -u /app/main.py --device_ip '' --audio_file /app/assets/audio_files/command_LED_yellow.mp3"]
