identifier = "com.luxonis.human-reidentification-example"

entrypoint = ["bash", "-c", "python3 /app/main.py <DET_MODEL> <REC_MODEL> <CSIM> <MEDIA> <FPS_LIMIT> <DEVICE>"]

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3 python3-pip libglib2.0-0 libgl1-mesa-glx wget git" },
]

build_steps = [
    "cd /app",
    "git clone -b v3_develop git@github.com:luxonis/depthai-core.git",
    "cd depthai-core",
    "python examples/python/install_requirements.py",
    "cd /app",
    "git clone git@github.com:luxonis/depthai-nodes.git",
    "cd depthai-nodes",
    "pip install -e .",
    "cd /app"
]

prepare_build_container = []