identifier = "com.luxonis.human-reidentification-example"

entrypoint = ["bash", "-c", "python3 /app/main.py <DET_MODEL> <REC_MODEL> <CSIM> <MEDIA> <FPS_LIMIT> <DEVICE>"]

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3 python3-pip libglib2.0-0 libgl1-mesa-glx wget git" },
]

build_steps = ["pip3 install -r /app/requirements.txt --break-system-packages"]

prepare_build_container = []