identifier = "com.luxonis.segmentation.background-blur"
app_version = "1.0.0"

prepare_container = [
    { type = "COPY", source = "requirements.txt", target = "requirements.txt" },
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3-pip" },
    { type = "RUN", command = "pip3 install -r /app/requirements.txt --break-system-packages" },
]

prepare_build_container = []

build_steps = []

entrypoint = ["bash", "-c", "python3 -u /app/main.py"]

depthai_models = { yaml_path = "./depthai_models" }