identifier = "com.luxonis.default"
app_version = "0.1.0"

prepare_container = [
    { type = "RUN", command = "apt-get update" },
    { type = "RUN", command = "apt-get install -y python3-pip" },
]

build_steps = ["pip3 install -r /app/requirements.txt --break-system-packages"]

prepare_build_container = []

entrypoint = ["bash", "-c", "python3 /app/main.py"]
