name: CI

on:
  pull_request:
    branches:
      - gen3

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install pre-commit
      run: python -m pip install 'pre-commit<4.0.0'

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1